---
abstract: 'Multiple virtual files at the end of your code'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Inline-Files
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: '0'
  Filter::Util::Call: '0'
  Test: '0'
resources:
  repository: https://gitlab.com/ambs/perl5-inline-files.git
version: '0.71'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
